### PR TITLE
September 2020 updates

### LINKED ISSUE #28: September 2020 Updates

### PR DESCRIPTION
**Pull request by ciprianjichici**
Closes #28 
Due to updates occurring after the initial fork, a rebase had to be performed (see commit 3737cf2) to avoid the need to solve merge conflicts in this PR.

Update 11/12: rebased to incorporate latest updates on master.

### CODE REVIEW

**Comment by nchandhi** [comment]
The architecture diagram doesnt seem to match the lab. The AutoML training process is not linked to Databricks job as I see from Lab instructions. please suggest if I am missing something.

image

**Comment by nchandhi** [comment]
Are the predictions supposed to be flat like this? I see a trend in timeseries but the red line is flat?

image

**Comment by nchandhi** [comment]
Package error in 2.0 Stream Scoring cmd 14:
image

**Comment by ciprianjichici** [comment]
I have re-tested all five labs to make sure there are no reproducible errors. Please make sure you are restoring the DBC lab archive from https://github.com/ciprianjichici/MCW-Machine-Learning/blob/master/Hands-on%20lab/notebooks/AI%20with%20Databricks%20and%20AML.dbc?raw=true, instead of the link specified in the content. The link in the lab setup guide content will become valid only after the PR is accepted (we used this approach to avoid committing to the repo any link pointing to the fork used for this PR).

With respect to the solution architecture, please make sure you are viewing the lab version that is part of this PR, which is properly aligned with the five labs in the DBC archive mentioned above: 
image

**Pull request merged**
